global using System.Diagnostics.CodeAnalysis;
global using System.Drawing.Drawing2D;
global using System.Reflection;
global using System.Runtime.InteropServices;
global using System.Text;
global using ALTTPSRAMEditor;
global using Library.Classes;
global using Library.Services;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using static ALTTPSRAMEditor.DrawCharHelper;
global using static ALTTPSRAMEditor.Properties.Resources;
global using static Library.Classes.Constants;
global using static Library.Classes.Enums;
